AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LambdaIamRole:
    Type: String
    Default: arn:aws:iam::315119964270:role/dl-fmwrk-lambda-role
  DlFmwrkPrefix:
    Type: String
    Default: dl-fmwrk
  Environment:
    Type: String
    Default: prod
  CodeBucket:
    Type: String
    Default: dl-fmwrk-code-us-east-2
  CodeBucketPath:
    Type: String
    Default: aws-datalake-framework-api/zip-files

Resources:
  DataAssetAPI:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      FunctionName: !Sub "aws-${DlFmwrkPrefix}-data-asset-api-${Environment}"
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Sub "${Environment}/${CodeBucketPath}/aws-dl-fmwrk-data-asset-api.zip"
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaIamRole
      Runtime: python3.7
      Environment:
        Variables:
          aws_account: 315119964270
          secret_name: dl-fmwrk-metadata-dev
          secret_region: us-east-2
          stage: !Ref Environment
      Layers:
        - !Ref LambdaLayer
      Timeout: 10
      FileSystemConfigs:
        - Arn: arn:aws:elasticfilesystem:us-east-2:315119964270:access-point/fsap-0ee24f7bd919419e8
          LocalMountPath: /mnt/dags
      VpcConfig:
        SecurityGroupIds:
          - sg-0fc188bdecea72d69
        SubnetIds:
          - subnet-0ff94b02df415f0ec
  DataAssetCatalogAPI:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      FunctionName: !Sub "aws-${DlFmwrkPrefix}-data-catalog-api-${Environment}"
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Sub "${Environment}/${CodeBucketPath}/aws-dl-fmwrk-data-asset-catalogs-api.zip"
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaIamRole
      Runtime: python3.7
      Environment:
        Variables:
          aws_account: 315119964270
          secret_name: dl-fmwrk-metadata-dev
          secret_region: us-east-2
          stage: !Ref Environment
      Layers:
        - !Ref LambdaLayer
      VpcConfig:
        SecurityGroupIds:
          - sg-02a41940cc6aa1be3
        SubnetIds:
          - subnet-0e40a1516e02514f8
          - subnet-0d747334837f4c777
  DataAssetInfoAPI:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      FunctionName: !Sub "aws-${DlFmwrkPrefix}-data-asset-info-api-${Environment}"
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Sub "${Environment}/${CodeBucketPath}/aws-dl-fmwrk-data-asset-info-api.zip"
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaIamRole
      Runtime: python3.7
      Environment:
        Variables:
          aws_account: 315119964270
          secret_name: dl-fmwrk-metadata-dev
          secret_region: us-east-2
          stage: !Ref Environment
      Layers:
        - !Ref LambdaLayer
      VpcConfig:
        SecurityGroupIds:
          - sg-02a41940cc6aa1be3
        SubnetIds:
          - subnet-0e40a1516e02514f8
          - subnet-0d747334837f4c777
  SourceSystemAPI:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      FunctionName: !Sub "aws-${DlFmwrkPrefix}-source-system-api-${Environment}"
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Sub "${Environment}/${CodeBucketPath}/aws-dl-fmwrk-source-system-api.zip"
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaIamRole
      Runtime: python3.7
      Environment:
        Variables:
          aws_account: 315119964270
          db_region: us-east-2
          db_secret: dl-fmwrk-metadata-dev
          region: us-east-2
          stage: !Ref Environment
      Layers:
        - !Ref LambdaLayer
      VpcConfig:
        SecurityGroupIds:
          - sg-02a41940cc6aa1be3
        SubnetIds:
          - subnet-0e40a1516e02514f8
          - subnet-0d747334837f4c777
      Timeout: 12
  TargetSystemAPI:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      FunctionName: !Sub "aws-${DlFmwrkPrefix}-target-system-api-${Environment}"
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Sub "${Environment}/${CodeBucketPath}/aws-dl-fmwrk-target-system-api.zip"
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaIamRole
      Runtime: python3.7
      Environment:
        Variables:
          aws_account: 315119964270
          rs_secret: dl-fmwrk-redshift-dev
          db_secret: dl-fmwrk-metadata-dev
          region: us-east-2
          stage: !Ref Environment
      Layers:
        - !Ref LambdaLayer
      Timeout: 10
      VpcConfig:
        SecurityGroupIds:
          - sg-02a41940cc6aa1be3
        SubnetIds:
          - subnet-0e40a1516e02514f8
          - subnet-0d747334837f4c777
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
        - python3.9
      CompatibleArchitectures:
        - x86_64
      Content:
        S3Bucket: !Ref CodeBucket
        S3Key: !Sub "${Environment}/aws-datalake-framework-api/dependencies/python.zip"
      Description: Layer to connect to database
      LayerName: dl_fmwrk_pg_connector
Outputs:
  LambdaDeployment:
    Description: Latest Commit to be updated here
    Value: Updated lambda functions
